### ISSUE TITLE
path issue / 

### ISSUE THREAD

**Issue by EleSangwon** [EleSangwon/Refactoring-Kubeboard#8]
Error: ENOENT: no such file or directory, open '/client-resource/node_resource.json'
    at Object.openSync (fs.js:498:3)
    at Object.readFileSync (fs.js:394:35)
    at exports.nodeInfo (/Users/bolt.lee/Desktop/devops-bolt/bolt-github/personal/Refactoring-Kubeboard/frontend/main/routes/info.js:6:6)
    at Layer.handle [as handle_request] (/Users/bolt.lee/Desktop/devops-bolt/bolt-github/personal/Refactoring-Kubeboard/frontend/main/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/bolt.lee/Desktop/devops-bolt/bolt-github/personal/Refactoring-Kubeboard/frontend/main/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/bolt.lee/Desktop/devops-bolt/bolt-github/personal/Refactoring-Kubeboard/frontend/main/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/bolt.lee/Desktop/devops-bolt/bolt-github/personal/Refactoring-Kubeboard/frontend/main/node_modules/express/lib/router/layer.js:95:5)
    at /Users/bolt.lee/Desktop/devops-bolt/bolt-github/personal/Refactoring-Kubeboard/frontend/main/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/bolt.lee/Desktop/devops-bolt/bolt-github/personal/Refactoring-Kubeboard/frontend/main/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/bolt.lee/Desktop/devops-bolt/bolt-github/personal/Refactoring-Kubeboard/frontend/main/node_modules/express/lib/router/index.js:275:10)

**Comment by EleSangwon** [comment]
FE 가 잘 동작하는 지 확인하기 위해 서비스 타입을 LB로 설정하면,  아래와 같은 에러가 발생한다. 
Error: ENOENT: no such file or directory, open '/client-resource/node_resource.json' 

EFS 에 대한 설정 빼놔서, 에러가 발생했는데 추후에 EFS -> DB로 마이그레이션한다면 FE 코드 수정이 필요
